feat: integrated Quartz.Net, implement FailedStrategy, TimeoutStrategy, BlockStrategy
masastack/MASA.Scheduler pull request #10
Opened 2022-06-22 06:43 UTC by gavin1ee

2022-06-23 01:41 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Services/SchedulerServerManagerService.cs
> +using Masa.Scheduler.Contracts.Server.Model;
global using

2022-06-23 02:09 UTC, MayueCif commented on src/Contracts/Masa.Scheduler.Contracts.Server/Infrastructure/IntegrationEvents/StartWaittingTaskIntergrationEvent.cs
> +public record StartWaittingTaskIntergrationEvent : IntegrationEvent
Waitting?

2022-06-23 03:18 UTC, MayueCif commented on src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerTasks.razor.cs
> +        Page++;
Upper limit？

2022-06-23 03:30 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Application/Jobs/SchedulerJobCommandHandler.cs
> +        await _quartzUtils.RemoveCronJob(job.Id);
move to QuartzUtils schedulerJobDomainService

2022-06-23 03:33 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/EventHandler/NotifyTaskRunResultDomainEventHandler.cs
> +    public NotifyTaskRunResultDomainEventHandler(IRepository<SchedulerTask> schedulerTaskRepository, SchedulerDbContext dbContext, IRepository<SchedulerJob> schedulerJobRepository, IHubContext<Notifi
to many params can format
![image](https://user-images.githubusercontent.com/6133287/175203245-17cfd3fb-2f7e-48e9-bfc1-df81bb9d20aa.png)

2022-06-23 03:39 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/EventHandler/RegisterCronJobDomainEventHandler.cs
> +        if(@event.Request.Data.ScheduleType == ScheduleTypes.Cron && !string.IsNullOrEmpty(@event.Request.Data.CronExpression))
IsNullOrWhiteSpace

2022-06-23 05:07 UTC, MayueCif commented on src/Web/Masa.Scheduler.Web.Admin.Server/wwwroot/i18n/zh-CN.json
>    "TimeoutSuccess": "超时成功",
超时(成功)

2022-06-23 05:08 UTC, MayueCif commented on src/Web/Masa.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobJobs.razor.cs
> +        Page++;
Upper limit？

2022-06-23 05:09 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Managers/Servers/SchedulerServerManager.cs
> +        await RegisterCronJob();
RegisterCronJobAsync

2022-06-23 05:10 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Managers/Servers/SchedulerServerManager.cs
> +        await LoadRunningTask(allTask);
Async suffix

2022-06-23 05:16 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Worker/Domain/Managers/Workers/TaskHandlers/JobAppTaskHandler.cs
> +    private void JobApp_Exit(object? sender, EventArgs e)
remove _

2022-06-23 05:18 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Worker/Domain/Managers/Workers/TaskHandlers/JobAppTaskHandler.cs
> +    private void JobApp_ErrorDataReceived(object? sender, System.Diagnostics.DataReceivedEventArgs e)
remove _

2022-06-23 05:19 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Worker/Domain/Managers/Workers/TaskHandlers/JobAppTaskHandler.cs
> +            await using var fs = File.Create(filePath);
await?

2022-06-23 05:23 UTC, MayueCif commented on src/Shells/Masa.Scheduler.Shells.JobShell/Program.cs
> +if(assembly == null)
move to catch

2022-06-23 05:24 UTC, MayueCif reviewed
@gavin1ee

2022-06-23 10:03 UTC, MayueCif approved these changes
@doddgu

2022-06-24 02:18 UTC, doddgu requested changes

2022-06-24 02:18 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Infrastructure/Quartz/QuartzUtils.cs
> +    public QuartzUtils(ISchedulerFactory schedulerFactory)
add blank line.

2022-06-24 02:18 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/QuartzJob/StartSchedulerTaskQuartzJob.cs
> +    public StartSchedulerTaskQuartzJob(IDomainEventBus eventBus)
add blank line.

2022-06-24 02:18 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/QuartzJob/StartSchedulerJobQuartzJob.cs
> +    public StartSchedulerJobQuartzJob(IDomainEventBus eventBus)
add blank line.

2022-06-24 02:18 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Properties/launchSettings.json
> +      "applicationUrl": "http://localhost:50672/",
See the port rule from confluence.

2022-06-24 02:40 UTC, doddgu approved these changes
LGTM

2022-06-24 02:41 UTC, merged