feat(domain model): add scheduler domain aggregates
masastack/MASA.Scheduler pull request #3
Opened 2022-05-09 09:13 UTC by gavin1ee

add scheduler domain aggregates

2022-05-10 07:33 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Dtos/JobDto.cs
> +public class JobDto
job or scheduler?

2022-05-10 07:40 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Infrastructure/Enums/ScheduleTypes.cs
> +    CRON
CRON?

2022-05-10 07:41 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Infrastructure/Enums/TaskRunStatus.cs
> +public enum TaskRunStatus
TaskRunStatuses

2022-05-10 07:42 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/Job.cs
> +    public Guid ResourceId { get; set; }
private

2022-05-10 07:44 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Tasks/SchedulerTask.cs
> +    public bool IsDeleted { get; set; }
private

2022-05-10 10:47 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Shared/MainLayout.razor
> +    <MAppBar Elevation=0 App MaxHeight=60 Class="mx-6 rounded-b-4")">
loss (

2022-05-10 10:47 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Global/Config/PageModes.cs
> +public static class PageModes
remove this file

2022-05-10 10:48 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Data/Shared/Favorite/FavoriteService.cs
> +namespace Masa.Scheduler.Web.Admin.Data.Shared.Favorite;
delete this file

2022-05-10 10:48 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Data/Dashboard/ECommerce/ECommerceService.cs
> +﻿// Copyright (c) MASA Stack All rights reserved.
delete this file

2022-05-10 11:58 UTC, MayueCif requested changes
modify

2022-05-12 05:00 UTC, MayueCif approved these changes

2022-05-12 05:01 UTC, MayueCif commented
@doddgu  LGTM

2022-05-13 04:58 UTC, doddgu requested changes

2022-05-13 04:58 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Application/Jobs/SchedulerJobQueryHandler.cs
> +    public SchedulerJobQueryHandler(ISchedulerJobRepository schedulerJobRepository)
add a blank line.

2022-05-13 04:58 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/SchedulerJobRunDetail.cs
> +    public DateTimeOffset LastRunTime { get; private set; }
Run -> Ran

2022-05-13 04:58 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/SchedulerJobRunDetail.cs
> +    public TaskRunStatuses LastRunStatus { get; private set; }
Run -> Ran, past tense

2022-05-13 04:58 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Tasks/SchedulerTask.cs
> +    public DateTimeOffset? TaskRunStartTime { get; private set; }
Use a default time instead of null.

2022-05-13 04:58 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Infrastructure/Repositories/SchedulerJobRepository.cs
> +    public async Task<List<SchedulerJob>> GetListAsync()
Add a blank line

2022-05-13 04:58 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Services/SchedulerJobService.cs
> +        App.MapPost("/createJob", CreateJob);
Post is create.

2022-05-13 05:13 UTC, gavin1ee commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Callers/JobCaller.cs
> +    public async Task<List<SchedulerJobDto>> GetListAsync()
It will remove in branch feature/project.  The caller will name SchedulerCall,  it has a service name SchedulerJobService like Auth

2022-05-13 05:17 UTC, gavin1ee commented on src/Contracts/MASA.Scheduler.Contracts.Server/Dtos/SchedulerJobDto.cs
> +    public string Principal { get; set; } = string.Empty;
Rename to ResponsiblePerson

2022-05-16 03:29 UTC, doddgu requested changes

2022-05-16 03:29 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/SchedulerJob.cs
> +    public bool IsEnabled { get; private set; }
Enabled

2022-05-16 03:29 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/SchedulerJobRunDetail.cs
> +    public DateTimeOffset LastRanTime { get; private set; } = DateTimeOffset.MinValue;
It looks a little weird. Maybe we should change it back.

2022-05-16 03:29 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/SchedulerJobRunDetail.cs
> +    public DateTimeOffset LastRanTime { get; private set; } = DateTimeOffset.MinValue;
It looks a little weird. Maybe we should change it back.

2022-05-16 03:36 UTC, doddgu approved these changes
LGTM

2022-05-16 03:36 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/SchedulerJob.cs
> +    public bool IsEnabled { get; private set; }
Enabled

2022-05-16 03:36 UTC, merged