feat(Team&Project): add team and project list
masastack/MASA.Scheduler pull request #4
Opened 2022-05-16 03:51 UTC by gavin1ee

add team and project list

2022-05-16 05:15 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Masa.Scheduler.ApiGateways.Caller.csproj
> +    <PackageReference Include="Masa.Utils.Caller.HttpClient" Version="0.4.0-preview.4" />
update rc

2022-05-16 05:18 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/SchedulerServerCaller.cs
> +    public SchedulerServerCaller(IServiceProvider serviceProvider, SchedulerApiOptions options) : base(serviceProvider)
IOptions<SchedulerApiOptions>

2022-05-16 05:23 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/ServiceCollectionExtensions.cs
> +        var option = new SchedulerApiOptions("http://localhost:16002");
should remove hard code,masa.auth is wrong demo

2022-05-16 05:55 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Services/AuthService.cs
> +    public async Task<List<TeamModel>> GetTeamListAsync()
Add Masa.BuildingBlocks.Service.Contracts ,user XXXXRequest and XXXResponse

2022-05-16 05:55 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Services/PMService.cs
> +    public async Task<List<ProjectModel>> GetProjectListAsync(Guid teamId)
ProjectModel modify

2022-05-16 05:56 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Services/SchedulerJobService.cs
> +    public async Task<List<SchedulerJobDto>> GetListAsync()
Add SchedulerJobResponse

2022-05-16 05:57 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Application/Teams/TeamQueryHandler.cs
> +
delete blank line

2022-05-16 06:01 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Pages/Teams/Team.razor
> +
delete blank line

2022-05-16 06:02 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Pages/Teams/Team.razor.cs
> +
delete line

2022-05-16 06:03 UTC, MayueCif requested changes
modify with conversation

2022-05-17 01:13 UTC, doddgu approved these changes
.

2022-05-17 02:58 UTC, MayueCif approved these changes

2022-05-17 02:58 UTC, MayueCif commented
@doddgu  LGTM

2022-05-17 05:56 UTC, doddgu requested changes

2022-05-17 05:56 UTC, doddgu commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Services/SchedulerJobService.cs
> +        BaseUrl = "api/job/";
scheduler job? job?

2022-05-17 05:56 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Services/SchedulerJobService.cs
> +    public SchedulerJobService(IServiceCollection services) : base(services, "api/job")
scheduler job? job?

2022-05-17 07:17 UTC, doddgu approved these changes
LGTM

2022-05-17 07:17 UTC, merged