feat: SchedulerJob module CURD
masastack/MASA.Scheduler pull request #5
Opened 2022-05-17 07:52 UTC by gavin1ee

SchedulerJob module CURD

2022-05-18 02:08 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Dtos/SchedulerJobHttpConfigDto.cs
> +    public Dictionary<string, string> HttpParameter { get; set; } = new Dictionary<string, string>();
HttpParameters

2022-05-18 02:09 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Dtos/SchedulerJobHttpConfigDto.cs
> +    public string HttpBody { get; set; } = string.Empty;
JsonObject better?

2022-05-18 02:21 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Infrastructure/Enums/HttpVerifyTypes.cs
> +    ContentDoesNotContain,
ContentUnContains

2022-05-18 02:25 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Requests/SchedulerJobListRequest.cs
> +    public int Page { get; set; }
define a PaginationRequest include Page and PageSize replace BaseRequest

2022-05-18 02:26 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Validator/SchedulerJobValidator.cs
> +public class SchedulerJobValidator<T> : AbstractValidator<T> where T : SchedulerJobDto
SchedulerJobDtoValidator

2022-05-18 02:29 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Validator/SchedulerJobValidator.cs
> +public class SchedulerJobValidator<T> : AbstractValidator<T> where T : SchedulerJobDto
why AbstractValidator<T>?  has inheritance?

2022-05-18 02:30 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/Configs/SchedulerJobAppConfig.cs
> +public class SchedulerJobAppConfig
lose inherit

2022-05-18 02:36 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Aggregates/Jobs/Configs/SchedulerJobHttpConfig.cs
> +    public Dictionary<string, string> HttpParameter { get; private set; } = new();
HttpParameters

2022-05-18 02:47 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Application/Jobs/SchedulerJobQueryHandler.cs
> +        condition = condition.And(request.IsCreatedByManual, job => job.Origin == string.Empty);
cumbersome write. following appear in pairs code。

2022-05-18 02:50 UTC, MayueCif requested changes
TBR

2022-05-23 07:59 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Requests/PaginationRequest.cs
> +public class PaginationRequest : BaseRequest
delete BaseRequest in project and add  Masa.BuildingBlocks.Service.Contracts replace

2022-05-23 08:00 UTC, MayueCif reviewed
replace BaseRequest

2022-05-23 08:03 UTC, MayueCif approved these changes

2022-05-23 08:04 UTC, MayueCif commented
@doddgu

2022-05-24 04:58 UTC, doddgu requested changes

2022-05-24 04:58 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Services/SchedulerJobService.cs
> +        var comman = new RemoveSchedulerJobCommand(jobId);
comman?

2022-05-24 05:06 UTC, doddgu approved these changes
LGTM

2022-05-24 05:06 UTC, merged