feat: Task & Manager
masastack/MASA.Scheduler pull request #6
Opened 2022-05-26 08:32 UTC by gavin1ee

Task CURD, StartTask, StopTask, SchedulerServerManager regist and assign Task to worker.  SchedulerWorkerManager regist and run HttpJob

2022-05-27 01:20 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Services/SchedulerJobService.cs
> +        return result ?? new(0, 0, new());
new(0, 0, new()) ==? new(new())

2022-05-27 01:23 UTC, MayueCif commented on src/ApiGateways/Caller/Masa.Scheduler.ApiGateways.Caller/Services/SchedulerJobService.cs
>          var result = await GetAsync<SchedulerJobListRequest,SchedulerJobListResponse>(string.Empty, request);
string.Empty ?

2022-05-27 01:27 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Dtos/SchedulerTaskDto.cs
> +
comment minutes or seconds?

2022-05-27 01:30 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Infrastructure/IntegrationEvents/BaseIntegrationEvent.cs
> +    public Guid ProgramId { get; set; }
ProgramId?

2022-05-27 01:45 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Infrastructure/IntegrationEvents/OnlineIntegrationEvent.cs
> +    public bool IsResponse { get; set; }
IsPong

2022-05-27 01:53 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Model/WorkerModel.cs
> +    public int CurrentRunTaskCount { get; set; }
CurrentTaskRunCount?

2022-05-27 01:58 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Requests/SchedulerTasks/NotifySchedulerTaskRunResultRequest.cs
> +    public bool IsSuccess { get; set; }
enum replace IsSuccess and IsCancel

2022-05-27 02:49 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Model/BaseServiceModel.cs
> +        if (HttpsPort != 0)
HttpsPort  has value but HttpsHost no value,HttpsHost  should main condition and handle 80、443

2022-05-27 02:55 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/EventHandler/NotifyTaskRunResultDomainEventHandler.cs
> +            return;
need a prompt？

2022-05-27 03:20 UTC, MayueCif reviewed
modify by conversation

2022-05-30 04:24 UTC, MayueCif approved these changes

2022-05-30 04:24 UTC, MayueCif commented
@doddgu LGTM

2022-05-30 09:06 UTC, doddgu requested changes

2022-05-30 09:06 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Application/Tasks/Commands/StartSchedulerTaskCommand.cs
> +public record StartSchedulerTaskCommand (StartSchedulerTaskRequest Request) : Command;
What's the different between `SchedulerTaskStartCommand` and `StartSchedulerTaskCommand`?

2022-05-30 09:46 UTC, gavin1ee commented on src/Services/Masa.Scheduler.Services.Server/Application/Tasks/Commands/StartSchedulerTaskCommand.cs
> +public record StartSchedulerTaskCommand (StartSchedulerTaskRequest Request) : Command;
SchedulerTaskStartCommand  是当Worker通知Server某个Task 启动时. Server的处理command.  
StartSchedulerTaskCommand  是当用于在页面上点击运行job/运行任务时. Server的处理command. 实际上Task还未真正开始运行. 只是把Task 丢给了Worker. 由Worker 运行.
目前为了防止混淆.  已经将SchedulerTaskStartCommand  改成了 NotifyTaskStartCommand

2022-05-31 08:12 UTC, doddgu approved these changes
LGTM

2022-05-31 08:12 UTC, merged