feat: Task query page & reactor manager & resolve bug
masastack/MASA.Scheduler pull request #8
Opened 2022-06-07 05:44 UTC by gavin1ee

Task query page & reactor manager & resolve bug

2022-06-08 01:45 UTC, MayueCif commented on src/Contracts/MASA.Scheduler.Contracts.Server/Infrastructure/Managers/BaseSchedulerManager.cs
> +using Masa.Utils.Security.Cryptography;
global using

2022-06-08 01:53 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/EventHandler/NotifyTaskRunResultDomainEventHandler.cs
> +            case TaskRunStatus.Timeout:
change to :
var message = XXX switch
{
  TaskRunStatus.Success=>"",
TaskRunStatus.Timeout=>"",
}

2022-06-08 01:56 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Managers/Servers/SchedulerServerManager.cs
> +        if(uri.Scheme == "http")
add SchemeConst

2022-06-08 01:57 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Managers/Servers/SchedulerServerManager.cs
> +                            await Task.Delay(1000);
?

2022-06-08 01:57 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Domain/Managers/Servers/SchedulerServerManager.cs
> +                    await Task.Delay(1000);
?

2022-06-08 02:03 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Pages/Teams/Components/Projects.razor.cs
> +
delete blanl line

2022-06-08 02:05 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobJobs.razor.cs
> +            if (_project?.Id != value?.Id)
_project and value both null

2022-06-08 02:11 UTC, MayueCif requested changes
modify

2022-06-08 03:20 UTC, MayueCif approved these changes

2022-06-08 03:20 UTC, MayueCif commented
@doddgu

2022-06-09 01:49 UTC, doddgu requested changes

2022-06-09 01:49 UTC, doddgu commented on src/Contracts/MASA.Scheduler.Contracts.Server/Masa.Scheduler.Contracts.Server.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.5" />
Why contacts depend on EF?

2022-06-09 01:49 UTC, doddgu commented on src/Web/MASA.Scheduler.Web.Admin/Masa.Scheduler.Web.Admin.csproj
> +    <Content Update="C:\Users\liguanyao\.nuget\packages\masa.blazor.experimental.components\0.2.6\contentFiles\any\net6.0\wwwroot\css\experimental.css">
`C:\Users\liguanyao\`?

2022-06-09 01:49 UTC, doddgu commented on src/Web/MASA.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobJobs.razor.cs
> +
remove the blank line

2022-06-09 01:49 UTC, doddgu commented on src/Web/MASA.Scheduler.Web.Admin/Pages/Teams/Components/SchedulerJobJobs.razor.cs
> +
remove the blank line

2022-06-10 03:37 UTC, doddgu approved these changes
LGTM

2022-06-10 03:37 UTC, merged