feat: Scheduler Resource CURD and web page
masastack/MASA.Scheduler pull request #9
Opened 2022-06-14 02:22 UTC by gavin1ee

add Scheduler Resource CURD and web page

2022-06-14 03:48 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Application/Resources/Queries/SchedulerResourceQuery.cs
> +public record SchedulerResourceQuery(SchedulerResourceListRequest Request) : Query<SchedulerResourceListResponse>
SchedulerResourcesQuery  or SchedulerResourceListQuery

2022-06-14 03:49 UTC, MayueCif commented on src/Services/Masa.Scheduler.Services.Server/Application/Resources/Queries/SchedulerResourceQuery.cs
> +    public override SchedulerResourceListResponse Result { get; set; } = null!;
new() replace null!

2022-06-14 05:25 UTC, MayueCif commented on src/Web/MASA.Scheduler.Web.Admin/Pages/SchedulerResources/SchedulerResourceFiles.razor.cs
> +    private const string PROJECT_PREFIX = "Project_";
const should be begin position

2022-06-14 05:28 UTC, MayueCif requested changes
@gavin1ee

2022-06-14 05:41 UTC, MayueCif approved these changes

2022-06-14 05:41 UTC, MayueCif commented
@doddgu LGTM

2022-06-20 06:35 UTC, doddgu requested changes

2022-06-20 06:35 UTC, doddgu commented on src/Services/Masa.Scheduler.Services.Server/Application/Resources/SchedulerResourceCommandHandler.cs
> +            throw new UserFriendlyException($"The current resource does not exist");
The exception message no need $ for it.

2022-06-20 06:47 UTC, doddgu approved these changes
LGTM

2022-06-20 06:47 UTC, merged